# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty


# Setup
title:            A Study of WebRTC Security
tagline:          'Ewan Leaver'
description:      "An open-source discussion on WebRTC security."
url:              http://webrtc-security.github.io

author:
  name:           'Ewan Leaver'
  url:            http://webrtc-security.github.io

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/webrtc-security/webrtc-security.github.io

exclude: [vendor]
